In [ ]:
import numpy as np
import random

row = np.array(eval(input('Masukkan 5 digit terakhir NPM : ')),dtype='float64') #input baris 4 berisi 5 digit NPM
arr = np.random.randint(100, size = (3,5)) #merandom entri matriks 3 x 5
aug_matrix = np.vstack([arr,row]) #menggabungkan list 'row' dengan matriks 'arr' 
print(' ')
print("Augmented matriks yang terbentuk dari SPL :")
print(aug_matrix)

print(' ')

def ScaledPartialPivoting(matrix): #mendefinisikan fungsi ScaledPartialPivoting
    n = np.shape(matrix)[0] #banyak baris pada matriks atau banyaknya persamaan pada SPL
    s = np.array([max(abs(matrix[i,:n])) for i in range(n)])  #menentukan skalar untuk setiap kolom
    if 0 in s:
        return "SPL tidak memiliki solusi unik" #elemen dengan nilai mutlak terbesar tidak boleh 0 (singular)
    for i in range(n-1):
        mutlak = abs(matrix[i:,i])/s[i:] #mencari |aik|/si
        pivot = np.argmax(mutlak) #mencari nilai maksimum dari numpy 'mutlak'
        if matrix[i,pivot+i] == 0:
            return "SPL tidak memiliki solusi unik" #elemen pivot tidak boleh 0 (singular)
        else:
            matrix[[pivot+i,i]] = matrix[[i,pivot+i]] #menukar baris (E1) <-> (E2)
            s[pivot+i],s[i] = s[i],s[pivot+i]
        
        for j in range(i+1,n): #for loop eleminasi gauss
            m = matrix[j,i]/matrix[i,i] #lakukan operasi baris elementer
            matrix[j] = matrix[j]-m*matrix[i]
        print(matrix)
        print(' ')
    return matrix

def BackSubs(matrix): #lakukan subtitusi balik
    n = np.shape(matrix)[0] #banyak baris pada matriks atau banyaknya persamaan pada SPL
    sol = np.zeros(n)  #membentuk array [0,0,...,0] sepanjang n, untuk menyimpan solusi
    sol[n-1]= matrix[n-1,n]/matrix[n-1,n-1] #menghitung xn
    for i in range(n-2,-1,-1): #substitusi balik dimulai
        for j in range(i+1,n):
            matrix[i,n] -= matrix[i,j]*sol[j]
        sol[i] = matrix[i,n]/matrix[i,i]
    return sol

solusiSPL = ScaledPartialPivoting(aug_matrix)
print("Solusi SPL : \n {0}".format(BackSubs(solusiSPL)))

Masukkan 5 digit terakhir NPM : [6,3,5,0,2]
 
Augmented matriks yang terbentuk dari SPL :
[[41. 79. 77. 62. 54.]
 [70. 23. 28. 81. 79.]
 [67.  8. 94. 12. 76.]
 [ 6.  3.  5.  0.  2.]]
 
[[  6.           3.           5.           0.           2.        ]
 [  0.         -12.         -30.33333333  81.          55.66666667]
 [  0.         -25.5         38.16666667  12.          53.66666667]
 [  0.          58.5         42.83333333  62.          40.33333333]]
 
[[  6.           3.           5.           0.           2.        ]
 [  0.          58.5         42.83333333  62.          40.33333333]
 [  0.           0.          56.83760684  39.02564103  71.24786325]
 [  0.           0.         -21.54700855  93.71794872  63.94017094]]
 
[[  6.           3.           5.           0.           2.        ]
 [  0.          58.5         42.83333333  62.          40.33333333]
 [  0.           0.          56.83760684  39.02564103  71.24786325]
 [  0.           0.           0.         108.5124812   90.950

Program ini adalah program untuk mencari solusi dari suatu SPL dengan salah satu strategi pivoting yaitu Scaled Partial Pivoting. Strategi pivoting adalah cara untuk mencegah masalah pada saat melakukan eliminasi Gauss dan substitusi balik muncul ketika *round-off error* dilibatkan dalam perhitungan. Biasanya masalah tersebut muncul ketika elemen pivot (entri diagonal pada matriks koefisien) cukup kecil bila dibandingkan dengan elemen di bawahnya, sehingga hasil substitusi balik bisa jauh dari solusi eksak. Strategi pivoting dilakukan dengan memilih elemen terbesar yang entrinya berada di bawah elemen pivot untuk menjadi pivot baru, kemudian menukar baris elemen pivot lama dengan yang baru.<br>

*__Scaled Partial Pivoting__* :
Definisikan $$s_i = \max_{1\leq j\leq n} |a_{ij}|$$.
Pilih $p \geq k$ terkecil sedemikian sehingga $$\frac{|a_{pk}^{(k)}|}{s_k}=\max_{k\leq i\leq n}\frac{|a_{ik}^{(k)}|}{s_i}$$
kemudian lakukan operasi $(E_k) \leftrightarrow (E_p)$.

Algoritmatnya adalah :
    1. Menginput baris terakhir matriks (dalam soal adalah 5 digit terakhir NPM mahasiswa).
    2. Merandom matriks berukuran 3x5 dengan nilai kurang dari 100.
    3. Menggabungkan input baris terakhir matriks dengan matriks random ukuran 3x5.
    4. Mendefinisikan suatu fungsi Scaled Partial Pivoting untuk menghitung strategi pivoting.
    5. Menentukan variabel s yaitu skalar mutlak maksimum dari masing-masing baris $s_i = \max_{1\leq j\leq n} |a_{ij}|$.
    6. Jika terdapat nilai maksimum 0, maka matriks tersebut singular atau tidak memiliki solusi unik.
    7. Menghitung nilai $\frac{|a_{pk}^{(k)}|}{s_k}=\max_{k\leq i\leq n}\frac{|a_{ik}^{(k)}|}{s_i}$.
    8. Jika terdapat elemen pivot 0, maka matriks tersebut singular atau tidak memiliki solusi unik.
    9. Lakukan operasi $(E_k) \leftrightarrow (E_p)$ yaitu menukar baris ke-k dengan baris ke-p.
    10. Lakukan eleminasi gauss dan operasi baris elementer.
    11. Lakukan subtitusi balik untuk mendapatkan solusi.